CREATE DATABASE IF NOT EXISTS `cuik`;

USE `cuik`;

CREATE TABLE IF NOT EXISTS `Users` (
    `id` BINARY(16) PRIMARY KEY,
    `name` VARCHAR(256) NOT NULL UNIQUE,
    `email` VARCHAR(256) NOT NULL UNIQUE,
    `pwdHash` VARCHAR(512) NOT NULL
);

CREATE TABLE IF NOT EXISTS `Employee` (
    `id` BINARY(16) PRIMARY KEY,
    `name` VARCHAR(256) NOT NULL UNIQUE,
    `email` VARCHAR(256) NOT NULL UNIQUE,
    `pwdHash` VARCHAR(512) NOT NULL,
    `isAdmin` BIT DEFAULT 0
);

\! echo 'Done.';